### ISSUE TITLE
swig.js release后directive前后没有空格。 运行时语法报错

### ISSUE THREAD

**Issue by kangxu2015** [fex-team/fis3-preprocessor-extlang#4]

**Comment by 2betop** [comment]
具体点？

**Comment by kangxu2015** [comment]
比如这样的代码{% widget "./widgetA.tpl" %} release后是{%widget"node:page/index/widgetA.tpl" %}
widget前后的空格不见了
.tpl => preprocessor: fis.plugin('extlang', {type: 'swig'}),

**Comment by 2betop** [comment]
fis3-preprocessor-extlang@1.1.9
